/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author USER
 */
public class Tank extends javax.swing.JFrame {

    /**
     * Creates new form Tank
     */
    public Tank() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        msgArea = new javax.swing.JTextArea();
        slider = new javax.swing.JSlider();
        txtSlider = new javax.swing.JTextField();
        btn2 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        sendMsgField = new javax.swing.JTextField();
        sendBtn = new javax.swing.JButton();
        areaClearLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        msgArea.setColumns(20);
        msgArea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        msgArea.setRows(5);
        jScrollPane1.setViewportView(msgArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 370, 110));

        slider.setMajorTickSpacing(10);
        slider.setOrientation(javax.swing.JSlider.VERTICAL);
        slider.setPaintLabels(true);
        slider.setPaintTicks(true);
        slider.setSnapToTicks(true);
        slider.setValue(0);
        getContentPane().add(slider, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 70, 240));

        txtSlider.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSlider.setText("0");
        txtSlider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSliderActionPerformed(evt);
            }
        });
        getContentPane().add(txtSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 90, 40));

        btn2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn2.setText("Ammo");
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 90, 30));

        btn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn1.setText("Shoot");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 90, 30));

        btn3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn3.setText("Missile");
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 90, 30));

        btn4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn4.setText("Army");
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 90, 30));

        sendMsgField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sendMsgField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMsgFieldActionPerformed(evt);
            }
        });
        getContentPane().add(sendMsgField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 260, 40));

        sendBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sendBtn.setText("Send");
        getContentPane().add(sendBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 70, 40));

        areaClearLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        areaClearLabel.setForeground(new java.awt.Color(255, 0, 0));
        areaClearLabel.setText("Area is Not Clear");
        getContentPane().add(areaClearLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 220, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSliderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSliderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSliderActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn1ActionPerformed

    private void sendMsgFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMsgFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendMsgFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tank().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel areaClearLabel;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea msgArea;
    private javax.swing.JButton sendBtn;
    private javax.swing.JTextField sendMsgField;
    private javax.swing.JSlider slider;
    private javax.swing.JTextField txtSlider;
    // End of variables declaration//GEN-END:variables
}
